rm -rf .repo/local_manifests;
rm -rf vendor/lineage-priv;
rm -rf vendor/oplus;
git clone https://github.com/ObsidianMaximus/local_manifests.git --depth 1 -b lineage-21 .repo/local_manifests;
/opt/crave/resync.sh;
rm vendor/lineage/build/soong/Android.bp;
rm vendor/lineage/config/BoardConfigSoong.mk;
rm frameworks/av/media/libmediaplayerservice/StagefrightRecorder.cpp;
rm frameworks/av/services/camera/libcameraservice/Android.bp;
rm frameworks/av/services/camera/libcameraservice/CameraService.cpp;
rm frameworks/av/services/camera/libcameraservice/CameraService.h;
rm frameworks/av/services/camera/libcameraservice/device3/Camera3Device.cpp;
rm build/soong/scripts/check_boot_jars/package_allowed_list.txt;
cd build/soong/scripts/check_boot_jars/;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_build_soong/lineage-21.0/scripts/check_boot_jars/package_allowed_list.txt;
cd -;
cd frameworks/av/media/libmediaplayerservice/;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_frameworks_av/lineage-21.0/media/libmediaplayerservice/StagefrightRecorder.cpp;
cd -;
cd frameworks/av/services/camera/libcameraservice/;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_frameworks_av/lineage-21.0/services/camera/libcameraservice/CameraService.cpp;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_frameworks_av/lineage-21.0/services/camera/libcameraservice/CameraService.h;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_frameworks_av/lineage-21.0/services/camera/libcameraservice/Android.bp;
cd -;
cd frameworks/av/services/camera/libcameraservice/device3/;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_frameworks_av/lineage-21.0/services/camera/libcameraservice/device3/Camera3Device.cpp;
cd -;
cd vendor/lineage/build/soong/;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_vendor_lineage/lineage-21.0/build/soong/Android.bp;
cd -;
cd vendor/lineage/config/;
curl -O https://raw.githubusercontent.com/ObsidianMaximus/android_vendor_lineage/lineage-21.0/config/BoardConfigSoong.mk; 
cd -;
source build/envsetup.sh;
breakfast bitra userdebug;
brunch bitra
