name: Build LineageOS 21

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: accupara-aosp

    steps:
      - name: Install Dependencies and repo tool
        run: |
          mkdir -p lineage
          cd lineage
          sudo apt-get update
          sudo apt-get install -y \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            flex \
            g++-multilib \
            gcc-multilib \
            git \
            git-lfs \
            gnupg \
            gperf \
            imagemagick \
            lib32readline-dev \
            lib32z1-dev \
            libelf-dev \
            liblz4-tool \
            libsdl1.2-dev \
            libssl-dev \
            libxml2 \
            libxml2-utils \
            lzop \
            pngcrush \
            rsync \
            schedtool \
            squashfs-tools \
            xsltproc \
            zip \
            zlib1g-dev
          
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+x ~/.bin/repo

          git config --global user.name "ProAndroidBuilder"
          git config --global user.email "android@veryrealemail.com"

          repo init -u https://github.com/LineageOS/android.git -b lineage-21.0 --depth=1
          mkdir -p .repo/local_manifests
          git clone https://github.com/ObsidianMaximus/local_manifests -b lineage-21 .repo/local_manifests
          repo sync -c --force-sync --optimized-fetch --no-tags --no-clone-bundle --prune -j$(nproc --all)
          rm -rf .repo  # Remove .repo folder to save space

          source build/envsetup.sh
          breakfast bitra userdebug
          brunch bitra

      - name: Upload build artifact
        id: upload-release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: lineage/out/target/product/bitra/*.zip
          asset_name: lineageos-21-bitra-$(date +'%Y%m%d').zip
          asset_content_type: application/zip
